<?php

require_once('yii.php');

/**
 * Test class for Formatter.
 * Generated by PHPUnit on 2009-04-09 at 10:54:00.
 */
class FormatterTest extends TestCase
{
    /**
     * @todo Implement testFileSize().
     */
    public function testFileSize() {

    	$this->assertEquals('0 B', Formatter::fileSize(0));

    	$this->assertEquals('1.00 KiB', Formatter::fileSize(1000));

    	$this->assertEquals('1.02 KiB', Formatter::fileSize(1024));

    	// Test fails due to floating point precision?
    	//$this->assertEquals('1.03 KiB', Formatter::fileSize(1025));

    	$this->assertEquals('1.03 KiB', Formatter::fileSize(1025.1));

    	$this->assertEquals('1.00 MiB', Formatter::fileSize(1000000));

    	$this->assertEquals('1.00 GiB', Formatter::fileSize(1000000000));

    	$this->assertEquals('1.00 TiB', Formatter::fileSize(1000000000000));

    	$this->assertEquals('1.00 PiB', Formatter::fileSize(1000000000000000));

    }
}

?>
