<?php

/**
 * Test class for SqlQuery.
 * Generated by PHPUnit on 2009-04-09 at 10:54:00.
 */
class SqlQueryTest extends TestCase
{

	public function testSplit()
	{

		$sql = 'DROP TABLE IF EXISTS `###DBPREFIX###sys_accesscontrol`;
					CREATE TABLE `###DBPREFIX###sys_accesscontrol` (
					  `accId` int(10) unsigned NOT NULL auto_increment,
					  `name` varchar(50) NOT NULL,
					  `pattern` varchar(250) NOT NULL,
					  `ipStart` varchar(15) default NULL,
					  `ipEnd` varchar(15) default NULL,
					  `enter` tinyint(1) unsigned NOT NULL,
					  `login` tinyint(1) unsigned NOT NULL,
					  `register` tinyint(1) unsigned NOT NULL,
					  PRIMARY KEY  (`accId`),
					  KEY `ipStart` (`ipStart`,`ipEnd`),
					  KEY `pattern` (`pattern`)
					) ENGINE=MyISAM DEFAULT CHARSET=utf8;';

		$sql .= "INSERT INTO `###DBPREFIX###acp_subgroup` (`asgId`, `lvaId`, `modId`, `order`, `agrId`) VALUES
			('layoutAppearance', 'global.w.appearance', 'sys', '10', 'layout'),
			('systemDatabase', 'global.w.database', 'sys', '30', 'system'),
			('usersExport', 'global.w.export', 'sys', '50', 'users'),
			('users', 'global.w.users', 'sys', '15', 'users'),
			('addonsDummy', 'DUMMY', 'sys', '1', 'addons'),
			('usersGroups', 'global.w.groups', 'sys', '10', 'users'),
			('systemMaintenance', 'global.p.maintenanceAndSecurity', 'sys', '20', 'system'),
			('systemSettings', 'global.w.settings', 'sys', '10', 'system'),
			('layoutAdvanced', 'global.w.advanced', 'sys', '20', 'layout'),
			('systemMisc', 'global.w.misc', 'sys', '100', 'system');";

		$sqlQuery = new SqlQuery($sql);

		$this->assertEquals(2, count($sqlQuery->queries));





	}

}

?>
